### ISSUE TITLE
Correct file name generation for forcing data

### ISSUE THREAD

**Issue by karnesh** [AlabamaWaterInstitute/data_access_examples#36]
Following code generates list of file names starting from f000 instead of f001 for medium range ( It works fine for short range):

```
start_date = "20221201"
end_date = "20221231"
short_f = list(range(1, 19))
medium_f = list(range(1, 241))

# forcings
configs = [
    (1, 5, 1, -1, start_date, end_date, short_f),  # Short_range
    (2, 5, 1, -1, start_date, end_date, medium_f),  # Medium range
]

prefix = ""
configuration_list = []
# configuration_list.extend([(*_c, start_date, end_date, "", 5) for _c in configs])
configuration_list.extend([(*_c, 5) for _c in configs]) # forcing

file_collections = [lnf.create_file_list(*_c) for _c in configuration_list]

```

Here is the first few list items 

['gcs://national-water-model/nwm.20221201/forcing_medium_range/nwm.t01z.medium_range.forcing.f000.conus.nc',
 'gcs://national-water-model/nwm.20221201/forcing_medium_range/nwm.t01z.medium_range.forcing.f001.conus.nc',
 'gcs://national-water-model/nwm.20221201/forcing_medium_range/nwm.t01z.medium_range.forcing.f002.conus.nc',
 'gcs://national-water-model/nwm.20221201/forcing_medium_range/nwm.t01z.medium_range.forcing.f003.conus.nc',
 'gcs://national-water-model/nwm.20221201/forcing_medium_range/nwm.t01z.medium_range.forcing.f004.conus.nc',
.....]

**Comment by jameshalgren** [comment]
closed by #37
